name_company = '//*[@id="companyId"]'
email1 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[4]/div/div[2]/div/span/a'
email2 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[4]/div/div[2]/div[2]/span/a'
email3 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[4]/div/div[2]/div[3]/span/a'
email4 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[4]/div/div[2]/div[4]/span/a'
kpp_company = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[2]/div/div[2]'
inn_company = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[1]/div/div[2]'
f_addres = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[2]/div/div[2]'
y_addres = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[4]/div/div[2]'
tel1 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div[2]/div[1]/span/a'
tel2 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div[2]/div[2]/span/a'
tel3 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div[2]/div[3]/span/a'
tel4 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div[2]/div[4]/span/a'
site = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div[4]/div/div[2]/div/span/span/a'
gendir = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[3]/div/div[2]'
okved2 = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[5]/div/div[2]'
date_reg = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[3]/div/div[6]/div/div[2]'
nalog_ot = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[4]/div/div/div/div[1]/div/div[2]'
indikator_riska = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[4]/div/div/div/div[2]/div/div[2]/text()'
indeks_DO = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[4]/div/div/div/div[4]/div/div[1]'
indeks_FR = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[4]/div/div/div/div[5]/div/div[1]'
viruchka = '/html/body/main/div[1]/div[2]/div/div/div[2]/div[2]/div[4]/div/div/div/div[6]/div/div[2]'
Aut1 = '/html/body/div[1]/section/section/div/div/div[2]/div[2]/div[2]/div[1]/div/form/button'
Aut2 = '/html/body/header/div[1]/div/div[2]/div[2]/div/a'
Aut3 = '/html/body/header/div[1]/div/div[2]/div[2]/div/div/a/div[2]'
Check = '/html/body/center[3]'


